### ISSUE TITLE
[South] - handle historians protocols with startDate and endDate

### ISSUE THREAD

**Issue by burgerni10** [OptimistikSAS/OIBus#1078]
Add a canHandleHistory=true; property for South protocols that can handle historians (like OPC-HDA, OPCUA, SQLDbToFile...)

For protocols that can handle historians, use a startDate and endDate to specify the timeframe of the requested data.

In run mode (the existing mode), when a request is trigger by a scan mode, startDate replaces lastCompletedAt and endDate is always now(). After the request, startDate=endDate.
In this mode, startDate can be set from the south protocol UI. Its value cannot be empty. A new timedatepicker component must be added for the UI.

**Comment by burgerni10** [comment]
A migration for lastCompletedAt may be necessary here.

**Comment by kukukk** [comment]
Right now the logic is the following:
 - first the database is checked for lastCompletedAt. If found, it will be used
 - if not found, startTime is checked in the config. If preset it will be used as lastCompletedAt
 - if not found new Date() will be used

It means that if lastCompletedAt is present in the database startDate/endDate from the config file won't be taken into account.
If I change the priority to check first startDate/endDate from the config it will use these values on the next start instead of the lastCompletedAt stored in the dabatase.
If both startDate and endDate is specified, when reaching endDate we should stop reading?

**Comment by marouanehassanioptimistik** [comment]
if we want to do this cleanly we need to have separate flows for realtime and historic. My guess is that if we try to mix both the logic will be flawed and the tool not as flexible

**Comment by burgerni10** [comment]
Following Marouane comment :
When a request is trigger in "run mode" : same as usual. LastCompletedDate should be displayed on the front though. It can be used to track the run mode with that. See issue #912. When an error occurs, it can still be useful to edit the LastCompletedDate from the UI (with a datetimepicker).

When a request is trigger in bulk : see issue #1079.

@jfhenon do you agree with that following your recent tests ?

**Comment by burgerni10** [comment]
To sum it up, for now canHandleHistory=true must be set in historian-supported protocols (SqlDbToFile, OPC-HDA, OPCUA-HA).

LastCompletedDate must be displayed on the connector UI. For multi-LastCompletedDate protocols (OPCUA-HA with Scan Groups for example), each scan group should display its own LastCompletedDate.

start/endDate will be implemented in bulk mode (see issue #1079) and the process may be merged later if necessary with 'run mode'.

**Comment by kukukk** [comment]
We had a discussion with @attilasuto about what should be the better logic and came up with the following:
 - canHandleHistory will be set to true in protocol implementation (not configurable on the UI)
 - when the UI requests the OIBus config will do an additional request which will contain the value of canHandleHistory for every added South (it is enough to request once, because it doesn't change)
 - on the South config UI, if canHandleHistory=true, the UI will periodically send a request to get the actual value of lastCompletedDate and update it on the UI (so the user will always see the actual value - with a small delay)

If live update is not important, the UI can make a single request to get lastCompletedAt and show it on the south config UI. But to actualize it the user will have to refresh the page.

Which one should we implement? Or do you prefer something else?

**Comment by burgerni10** [comment]
You can go with a single request and if we want an update, the user will refresh the page.

We will go further with live update of the UI in general later, when we improve JF branch poc-sse
