### ISSUE TITLE
When renaming a South/North, the corresponding sqlfile table is not renamed which potentially can cause loss of data.

### ISSUE THREAD

**Issue by jfhenon** [OptimistikSAS/OIBus#1191]
either
1/ we make sure the cache is empty before allowing a rename
2/ we rename the file as well (preferred I think)

**Comment by kukukk** [comment]
Hmm... Not sure if it so easy. The rename is done in the frontend. The backend knows nothing about the config change, just reads the actual config after restart. 

Maybe it would be better to use an additional `id`, which is hidden from the user. It should be generated by the frontend when a new North/South is added using UUID - which can be considered to be unique. This `id` would be the same after the North/South is renamed. The backend could use this `id` to identify the North/South in tables and to generate SQLite filenames.
We could also write a migration, which generates this `id` for every North/South and makes the necessary renames.

**Comment by jfhenon** [comment]
The frontend use the name in the URL as well so I don’t see this hidden Id as a preferred solution. Is it possible to ask for a rename to the backend? 
JF

Jean-François HÉNON - Optimistik
+33 6 03 79 73 26

**Comment by kukukk** [comment]
We could have a separate `id` and `name`, where `id` would be used by the backend and `name` by the frontend. We could even keep using applicationId and dataSourceId for `name`, so the frontend changes would be minimal (just generate the `id` when creating a new North/South)

Asking the backend for a rename could have some extra complications:
 - if we do this during runtime operation, the Cache must close the SQLite connection so the file can be renamed, but what do we do with new values during this time? 
 - if we do this with a restart of OIBus, we have to store somewhere the information about which North/South should be renamed, and handle it before the worker starts (similar to migrations).

Also, using a simple free text input as a source for the filename may not be a very good idea, because the user can introduce any special characters. Having a UUID `id` would eliminate this possible problem.

**Comment by burgerni10** [comment]
I totally agree with the `uuid` solution. 

After some talks with JF, his main concerns are about the simplicity of use in general (usage and debug). 
Being able to see to which connector each sqlite database is linked is useful. I suggest that the uuid can be displayed in the connector (and maybe in the south / north connector list) so if needed we can look into the sqlite database (can be done in another issue)
For the url, I don't think it is a problem to have an uuid instead of the name of the connector since it will still be displayed on the page thanks to the breadcrumb. Speaking of which, the breadcrumb should be reworked a bit to take this change into account (using the uuid in url and name for display)

This issue may need to be split in several smaller one to simplify code review. If we agree on the design, I'll add a database-rename/develop branch that will serve to base the smaller commits. @jfhenon what do you think ?
