### ISSUE TITLE
oibus.json config file could be retrieved from a rest API

### ISSUE THREAD

**Issue by jfhenon** [OptimistikSAS/OIBus#430]
Right now, the json file used to configure OIBus is retrieved from a local file (oibus.json for example). It may be a good idea to get this configuration from OIAnalytics (or another endpoint sucha as another OIBus). This may help to centralize configurations and also to make sure that points added into OIAnalytics are automatically inserted in the OIBus configuration. 
need more thinking.

**Comment by jfhenon** [comment]
I put a higher priority on this request. 
Basically, OIBus should be able to read part or all of the configuration (especially the list of points) from a remote API. Typically, we would like the end points (such as OIAnalytics where points are already configured) to be able to return the list of points so OIBus can update it. 
Few design points: 
- OIBus needs to request (we don't want to push to OIBus) 
- The OIBus requesting may have to go through another OIBus (when OIConnect is used) to access OIAnalytics
- The priority is the list of points for south protocols but we could imagine to have other configuration updated by this end point.

**Comment by kukukk** [comment]
Do you want a configuration option on the frontend to configure the remote data source from where the OIBus can request the information (url, user, pass) or do you prefer just a button on the frontend and, when it is pressed, a popup to enter the url, user, pass?
If you want to be able to go through another OIBus instance it may be easier to have a dedicated config entry for this. If this section is activated, the target OIBus installation will forward the request. Otherwise will respond with information from its local oibus.json.
Or do you want to make possible such situation when local OIBus uses remote1, target OIBus uses remote2 and local OIBus uses target OIBus as a proxy?

We will have to add some checks to be sure that the received configuration is valid.

**Comment by jfhenon** [comment]
- I think it's a configuration option that we need. For example with configSourceUrl= ...my oianalytics, When OIBus starts an configSourceUrl is enabled, it will use an API to be defined to query the config. 
- The configSource can be another OIBus, in that case, that other OIBus will query it's own configSourceUrl and will forward the content to the first OIBus.
- Indeed, we will need to review the form validation so they can be used on the frontend (today, they contain HTML content that we must turn into strings). I have another PR about this.

**Comment by kukukk** [comment]
Ahh, do you want OIBus to get the information on every start? I thought that it would be a one time action initiated by a user. In case of OIBus will do this on every start, we will have to think about the situation when the remote API is not accessible.

**Comment by jfhenon** [comment]
I think it should be on every start. If the remote API is not responding, we log it but we can keep the latest config.

**Comment by burgerni10** [comment]
OIBus now has several endpoints with CRUD operations for its entities.
